apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectorsphere-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vectorsphere-api
  template:
    metadata:
      labels:
        app: vectorsphere-api
    spec:
      containers:
        - name: api
          image: <DOCKERHUB_USERNAME>/vectorsphere:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "vectorsphere-redis"
            - name: WEAVIATE_HOST
              value: "vectorsphere-weaviate"
---
apiVersion: v1
kind: Service
metadata:
  name: vectorsphere-api
spec:
  selector:
    app: vectorsphere-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

